export default function() {
    return [
        { title: 'Inferno', pages: 666},
        { title: 'Paradiso', pages: 85},
        { title: 'Your mom', pages: 1 },
        { title: 'Purgatorio', pages: 314 },
    ]
}

//Redux serves to construct the application state, and React serves to create the views to display that application state
//Our application state is generated by reducer functions 

